package com.ubsvirtual.UbsVirtual.models.pessoas;

public enum Especializacao {
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GINECOLOGIA,
    NEUROLOGIA,
    ORTOPEDIA,
    PEDIATRIA,
    PSIQUIATRIA,
    UROLOGIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    CIRURGIA_GERAL,
    RADIOLOGIA,
    ONCOLOGIA,
    GASTROENTEROLOGIA,
    NEFROLOGIA,
    PNEUMOLOGIA,
    REUMATOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    ANESTESIOLOGIA,
    MEDICINA_INTENSIVA;


}
